# Generated by Django 2.0.5 on 2018-08-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='manga_cover',
        ),
    ]
