# Generated by Django 2.0.5 on 2018-08-22 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='mangachapter',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='mangachapter',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='image_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mangapage',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(to='navigation.Genre'),
        ),
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(to='navigation.Tag'),
        ),
    ]
