# Generated by Django 2.1.5 on 2019-01-31 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('navigation', '0003_manga_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='author',
        ),
        migrations.AddField(
            model_name='manga',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
