# Generated by Django 2.0.5 on 2018-08-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
