# Generated by Django 2.0.5 on 2018-08-22 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20180822_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='name',
            new_name='title',
        ),
    ]
